<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>MedApp.Client</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.20" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.20" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MedApp.Contracts\MedApp.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Shared\Components\Forms\FormGroups\DatePickerFormGroup.razor" />
      <_ContentIncludedByDefault Remove="Shared\Components\FormGroups\DatePickerFormGroup.razor" />
      <_ContentIncludedByDefault Remove="Shared\Components\Summaries\PatientSummary.razor" />
      <_ContentIncludedByDefault Remove="Components\Shared\Summaries\PatientSummary.razor" />
      <_ContentIncludedByDefault Remove="Components\Summaries\PatientSummary.razor" />
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="Components\Forms\FormCard.razor" />
      <AdditionalFiles Include="Components\Forms\FormGroup.razor" />
      <AdditionalFiles Include="Components\Forms\FormGroups\DatePickerFormGroup.razor" />
      <AdditionalFiles Include="Components\Forms\FormSection.razor" />
      <AdditionalFiles Include="Components\Pages\Page.razor" />
      <AdditionalFiles Include="Components\Pages\PageHeader.razor" />
      <AdditionalFiles Include="Components\Shared\AlertMessage.razor" />
      <AdditionalFiles Include="Components\Shared\Icon.razor" />
      <AdditionalFiles Include="Components\Shared\SummaryItem.razor" />
      <AdditionalFiles Include="Components\Views\ViewCard.razor" />
      <AdditionalFiles Include="Components\Views\ViewGroup.razor" />
      <AdditionalFiles Include="Components\Views\ViewSection.razor" />
    </ItemGroup>
</Project>
